import type { SketchEntry } from "../types";
import { spiralOne } from "./spiralOne";
import { spiralGira } from "./spiralGira";
import { girasol } from "./girasol";
import { generativo } from "./generativo";
import { generativoParticulas } from "./generativoParticulas";
import { spaceGame } from "./spaceGame";
import { mousePaint } from "./mousePaint";
import { rejillaMovimiento } from "./rejillaMovimiento";
import { arosPulsantes } from "./arosPulsantes";
import { bolitasVectores } from "./bolitasVectores";
// import { piano } from "./piano";
import { sumador } from "./sumador";
import { soundCollider } from "./soundCollider";
import { fftVisualization } from "./fftVisualization";
// import { reticulaCrayola } from "./reticulaCrayola";
// import { estacionEspacial } from "./estacionEspacial";
import { terrenoRuido } from "./terrenoRuido";
import { lineasHumo } from "./lineasHumo";
import { abanicosAgentes } from "./abanicosAgentes";
import { ondasModuladas } from "./ondasModuladas";
import { orbitasLissajous } from "./orbitasLissajous";
import { mallaArmonica } from "./mallaArmonica";
import { revolution } from "./revolution";
import { noiseCircle } from "./noiseCircle";
import { compAurea } from "./compAurea";
import { rev2 } from "./rev2";
import { rev3 } from "./rev3";
import { revNoiz } from "./revNoiz";
import { trayectorias } from "./trayectorias";
import { sunsetREv } from "./sunsetREv";
import { delay3 } from "./delay3";
import { spectografo } from "./spectografo";
import { audioGraf } from "./audioGraf";
import { synth } from "./synth";
import { atomosPixel } from "./atomosPixel";
import { florManos } from "./florManos";
import { florShader } from "./florShader";
import { mareaManos } from "./mareaManos";
import { mascaraTunel } from "./mascaraTunel";
import { fractalJulia } from "./fractalJulia";
import { cavernaImpulso } from "./cavernaImpulso";
import { filtrosCamara } from "./filtrosCamara";


const baseImage = "https://amazons3-images-micel10.s3.us-east-2.amazonaws.com/images/gallery/";
/**
 * Registro de piezas de la galería. Agregar una pieza nueva = portar su factory
 * y añadir una entrada aquí; la landing itera sobre este array.
 */
export const sketches: SketchEntry[] = [
    {
    meta: {
      slug: "generativo",
      title: "Generativo",
      author: "emm3",
      source: "p5_works/sketches/generativo.js",
      image: `${baseImage}generativo.png`,
      description: "Composición generativa: un patrón aleatorio de líneas que recorre y se acumula sobre el lienzo, una cuadrícula de elipses, un cuadrado central que gira y 5 círculos interactivos distribuidos en pentágono que laten y brillan solos como afordancia de clic. Paleta vívida café-negro/dorado/turquesa/magenta neón. Loop continuo, interactivo por mouse.",
      tags: ["generativo", "líneas", "cuadrícula", "interactivo", "afordancia"],
      controls: [
        { key: "mouse", action: "Mantener pulsado activa el color de acento en líneas, cuadrado y círculos interactivos." },
        { key: "s / S", action: "Guardar el canvas como PNG (saveCanvas)." },
      ],
      needsAudio: false,
      width: 600,
      height: 600,
    },
    factory: generativo,
  },
  {
    meta: {
      slug: "generativo-particulas",
      title: "Generativo Partículas",
      author: "emm3",
      source: "p5_works/sketches/generativoParticulas.js",
      image: `${baseImage}generativo-particulas.png`,
      description: "Campo de flujo de ruido Perlin (Coding Train): 300 partículas siguen el campo recalculado cada frame y dejan estelas de color que derivan lentamente en el tiempo y rebotan en los bordes. Paleta violeta-magenta-cian neón sobre fondo casi negro, con el color de cada partícula elegido por distribución gaussiana centrada en el violeta medio de la paleta. El cursor atrae (o repele, con clic) a las partículas cercanas. Reusa la biblioteca Particle extendida con el modo 'estela'.",
      tags: ["partículas", "flow field", "Perlin noise", "estela", "bibliotecas", "interactivo"],
      controls: [
        { key: "mouse", action: "El cursor atrae a las partículas cercanas; el radio de influencia es local." },
        { key: "clic", action: "Invierte el modo del cursor entre atraer y repeler." },
        { key: "s / S", action: "Guardar el canvas como PNG (saveCanvas)." },
      ],
      needsAudio: false,
      width: 600,
      height: 600,
    },
    factory: generativoParticulas,
  },
   {
    meta: {
      slug: "girasol",
      title: "Girasol",
      author: "emm3",
      source: "p5_works/sketches/girasol.js",
      image: `${baseImage}girasol.png`,
      description: "Girasol estático compuesto por cuatro espirales de partículas (centro, dos coronas de semillas y pétalos) sobre un cielo violeta synthwave, con corona y pétalos en neón naranja/ámbar. Estudio de composición polar; reusa la biblioteca Spiral y se detiene con noLoop() tras el primer frame.",
      tags: ["espiral", "partículas", "composición", "bibliotecas", "noLoop"],
      controls: [
        { key: "s", action: "Guardar el canvas como PNG (saveCanvas)." },
      ],
      needsAudio: false,
      width: 1254,
      height: 1254,
    },
    factory: girasol,
  },
  {
    meta: {
      slug: "spiral-gira",
      title: "Spiral Gira",
      author: "emm3",
      source: "p5_works/sketches/spiralGira.js",
      image: `${baseImage}spiral-gira.png`,
      description: "Flor animada de cuatro capas de espirales (centro, corona, semillas y pétalos, estos últimos con forma de gota) que respiran: los radios y ciclos hacen ping-pong entre límites mientras los offsets de ángulo rotan en sentidos contrarios. Reusa la biblioteca Spiral en modo instancia, con paleta propia en tonos ember/dorado.",
      tags: ["espiral", "partículas", "Nature of Code", "bibliotecas"],
      controls: [
        { key: "s", action: "Guardar el canvas como PNG (saveCanvas)." },
      ],
      needsAudio: false,
      width: 1080,
      height: 1080,
    },
    factory: spiralGira,
  },
   {
    meta: {
      slug: "spiral-one",
      title: "Spiral One",
      author: "mdrn.mx",
      source: "p5_works/sketches/spiralOne.js",
      image: `${baseImage}spiral-one.png`,  
      description: "Tres espirales concéntricas de partículas que respiran: el radio interior y exterior hacen ping-pong entre límites y los ciclos se animan con un offset de ángulo continuo. Ejercita el reuso de las bibliotecas Spiral y Particle en modo instancia.",
      tags: ["espiral", "partículas", "Nature of Code", "bibliotecas"],
      controls: [
        { key: "s", action: "Guardar el canvas como PNG (saveCanvas)." },
      ],
      needsAudio: false,
      width: 600,
      height: 600,
    },
    factory: spiralOne,
  },
    {
    meta: {
      slug: "rejilla-movimiento",
      title: "Ojos que no ven...",
      author: "emm3",
      source: "Talleres2021-CC1/assets/js/scripts/CC1/script/CC1_taller4_Movbolita_loopAnidado.js",
      image: `${baseImage}rejilla-movimiento.png`,
      description: "Rejilla de 64 ojos con estado propio: cada uno tiene tamaño, forma y color de iris distintos, y una pupila que persigue al cursor como en unos 'googly eyes'. Al hacer clic, los ojos más cercanos al punto tocado reaccionan cerrando el párpado (parpadeo) o dejando caer una lágrima, animados en el tiempo. La rejilla se calcula para llenar el canvas sin encimar ojos. Reescritura completa de la pieza original sin estado (círculos en trayectoria circular + ruido Perlin, fondo acumulado sin limpiar).",
      tags: ["ojos", "interactivo", "estado por objeto", "animación", "mouse"],
      controls: [
        { key: "mouse", action: "La pupila de cada ojo sigue al cursor." },
        { key: "clic", action: "Los ojos más cercanos al punto de clic parpadean o lloran." },
        { key: "s / S", action: "Guardar el canvas como PNG (saveCanvas)." },
      ],
      needsAudio: false,
      width: 800,
      height: 800,
    },
    factory: rejillaMovimiento,
  },
  {
    meta: {
      slug: "aros-pulsantes",
      title: "Aros Pulsantes",
      author: "emm3",
      source:
        "Talleres2021-CC1/assets/js/scripts/CC1/Ejemplos/CC1_ejemplo4_Movbolita_loopAnidado_aros.js",
      image: `${baseImage}aros-pulsantes.png`,
      description: "Rejilla de 49 celdas con estado propio (punto, aro y cuadrado en proporción áurea φ) y color HSB psicodélico que recorre el espectro con corrimiento de fase por celda. Dos de cada tres celdas laten con un pulso suave; la tercera rota con un rebote elástico amortiguado, para que se note la variación cada 3 iteraciones. Las celdas cercanas al mouse se energizan (más amplitud, velocidad y saturación) con una caída suave según la distancia. El tamaño base de cada celda es determinístico, calculado una vez con ruido Perlin.",
      tags: ["rejilla", "geometría", "pulso", "HSB", "proporción áurea", "interactivo", "psicodélico"],
      controls: [
        { key: "mouse", action: "Las celdas cercanas al cursor se energizan: más amplitud, velocidad y brillo." },
        { key: "s / S", action: "Guardar el canvas como PNG (saveCanvas)." },
      ],
      needsAudio: false,
      width: 600,
      height: 600,
    },
    factory: arosPulsantes,
  },
  {
    meta: {
      slug: "mouse-paint",
      title: "Mouse Paint",
      author: "emm3",
      source: "Talleres2021-CC1/assets/js/scripts/CC1/Ejemplos/CC1_ejemplo3_mousePaint.js",
      image: `${baseImage}mouse-paint.png`,
      description: "Herramienta de pintura por capas: el trazo se acumula sobre una capa persistente y el fondo se repinta detrás cada frame (cambiarlo no borra nada). Cinco brochas (cuadrado, circular, línea y las compuestas aerógrafo y rosetón), tamaño ajustable, selectores de color para fondo/brocha, y un modo de figura cerrada por vértices con borde y relleno propios. Ampliación de un ejercicio del taller de Introducción al Código Creativo de mndrn.mx.",
      tags: ["interactivo", "pintar", "brochas", "mouse", "figuras"],
      controls: [
        { key: "mouse", action: "Arrastrar pinta con la brocha activa; en modo figura, cada click coloca un vértice." },
        { key: "1-5", action: "Elegir brocha: cuadrado, circular, línea, aerógrafo, rosetón (vuelve a modo pincel)." },
        { key: "+ / -", action: "Aumentar / disminuir el tamaño de la brocha (también con los botones en pantalla)." },
        { key: "v", action: "Alternar entre modo pincel y modo figura (vértices)." },
        { key: "c", action: "Cerrar los vértices en una figura con borde y relleno seleccionables." },
        { key: "selectores", action: "Color de fondo, brocha, borde de figura y relleno de figura." },
        { key: "s", action: "Guardar el canvas como PNG (saveCanvas)." },
      ],
      needsAudio: false,
      width: 1000,
      height: 1000,
    },
    factory: mousePaint,
  },
  {
    meta: {
      slug: "bolitas-vectores",
      title: "Bolitas Ping-Pong",
      author: "emm3",
      source:
        "Talleres2021-CC1/assets/js/scripts/CC1/Ejemplos/CC1_ejemplo2.5._Bolita_vectores_Muchos.js",
      image: `${baseImage}bolitas-vectores.png`,
      description: "Cinco bolitas (antes tres) con posición y velocidad como vectores rebotan dentro de una frontera rectangular; cada rebote dispara una voz de un instrumento de campana/marimba (oscilador triangular → filtro pasa-banda resonante → envolvente percusiva, migrado a Tone.js), afinada según el tamaño de la bolita: chica suena aguda, grande suena grave. Un clic 'mata' la última bolita del arreglo y hace nacer una nueva con tamaño, velocidad, color y frecuencia distintos.",
      tags: ["partículas", "rebote", "vectores", "interactivo", "audio", "Tone.js", "percusión"],
      controls: [
        { key: "clic", action: "'Mata' la última bolita y hace nacer una nueva con tamaño, velocidad, color y frecuencia distintos (activa el audio)." },
        { key: "espacio", action: "Mostrar u ocultar la frontera." },
        { key: "s / S", action: "Guardar el canvas como PNG (saveCanvas)." },
      ],
      needsAudio: true,
      motorAudio: "tone",
      width: 600,
      height: 600,
    },
    factory: bolitasVectores,
  },{
    meta: {
      slug: "space-game",
      title: "Space Game",
      author: "emm3",
      source: "spaceGame/sketch.js",
      image: `${baseImage}space-game.png`,
      description: "Reimplementación en p5 del clásico canvas shooter: una nave triangular generativa (moverse con WASD, siempre orientada hacia el cursor) dispara al hacer clic; los enemigos surgen de los bordes en colores cyberpunk según su tamaño/resistencia y persiguen a la nave, al impactarlos encogen o explotan en partículas y suman score. Fondo de campo estelar persistente sobre negro profundo. El original era Canvas 2D vanilla + gsap; aquí se reescribe sobre p5 sin dependencias externas.",
      tags: ["juego", "interactivo", "colisiones", "partículas", "cyberpunk"],
      controls: [
        {
          key: "clic",
          action: "Disparar hacia el cursor; también inicia y reinicia la partida.",
        },
        { key: "g / G", action: "Guardar el canvas como PNG (saveCanvas)." },
        { key: "W / A / S / D", action: "Mover la nave por el lienzo (movimiento continuo)." },
      ],
      needsAudio: false,
      width: 800,
      height: 600,
    },
    factory: spaceGame,
  },
  {
    meta: {
      slug: "comp-aurea",
      title: "Composición Áurea",
      author: "emm3",
      source: "creativeCode/compAurea.js",
      image: `${baseImage}comp-aurea.png`,
      description: "Círculos translúcidos superpuestos cuyos diámetros crecen en proporción áurea (φ = 1.618), anclados a las esquinas y retículas de una rejilla, con un cuadrado central que rota. Reestilizada a los tokens del sitio conservando la variedad de tonos del original (verde matrix como base; violeta, ember, ámbar, orquídea y naranja re-mapeados 1-a-1 desde los matices originales para que cada capa se distinga), con un filtro CRT en postproceso —aberración cromática, scanlines, viñeta y flicker— cuya intensidad se modula con el ángulo de giro del cuadrado, más una familia de puntos de interés sembrados en espiral áurea. Loop continuo.",
      tags: ["proporción áurea", "geometría", "composición", "CRT", "postproceso"],
      controls: [{ key: "s", action: "Guardar el canvas como PNG (saveCanvas)." }],
      needsAudio: false,
      width: 1000,
      height: 1000,
    },
    factory: compAurea,
  },
  {
    meta: {
      slug: "noise-circle",
      title: "Noise Circle",
      author: "emm3",
      source: "creativeCode/noiseCircle.js",
      image: `${baseImage}noise-circle.png`,
      description: "Una línea cuyo extremo orbita el centro sobre un fondo negro persistente; el grosor, el brillo y la opacidad del trazo se modulan con ruido Perlin, dejando una estela verde que rellena el círculo, con un anillo intermedio de cuentas y ticks ámbar perimetrales que acumulan textura. El 'hola mundo' de la familia Revolución.",
      tags: ["órbita", "Perlin noise", "estela", "minimal"],
      controls: [
        { key: "clic", action: "Cambia puntero a amarillo" },
        { key: "s", action: "Guardar el canvas como PNG (saveCanvas)." },
      ],
      needsAudio: false,
      width: 1000,
      height: 1000,
    },
    factory: noiseCircle,
  },
  {
    meta: {
      slug: "sunset-rev",
      title: "Relieve Rev",
      author: "emm3",
      source: "creativeCode/sunsetREv.js",
      image: `${baseImage}sunset-rev.png`,
      description: "Relieve de montaña generativo (vertical) de la familia Revolución: una trayectoria circular con ruido traza líneas que se acumulan a lo largo de una franja temporal, con grosor y opacidad modulados por Perlin. Detrás, una bruma de líneas horizontales barre el canvas de arriba a abajo al ritmo del timeline, cada una con su propia opacidad por ruido. Termina con noLoop().",
      tags: ["timeline", "relieve", "Perlin noise", "bruma", "noLoop"],
      controls: [{ key: "s", action: "Guardar el canvas como PNG (saveCanvas)." }],
      needsAudio: false,
      width: 1080,
      height: 1350,
    },
    factory: sunsetREv,
  },
  {
    meta: {
      slug: "revolution",
      title: "Revolution",
      author: "emm3",
      source: "creativeCode/revolution.js",
      image: `${baseImage}revolution.png`,
      description: "Paisaje radial trazado en HSB, arquetipo de la familia Revolución: dos ángulos contrarrotantes tejen líneas moduladas por ruido Perlin en grosor y opacidad, con un anillo perimetral de puntos ámbar y ecos radiales interiores que exponen el mismo ruido. La pieza es de duración fija: al completar una vuelta (angle ≥ TWO_PI) dibuja un remate de cuadrados y se detiene con noLoop().",
      tags: ["radial", "HSB", "Perlin noise", "noLoop"],
      controls: [{ key: "s", action: "Guardar el canvas como PNG (saveCanvas)." }],
      needsAudio: false,
      width: 1000,
      height: 1000,
    },
    factory: revolution,
  },  
  {
    meta: {
      slug: "rev2",
      title: "Revolution II",
      author: "emm3",
      source: "creativeCode/rev2.js",
      image: `${baseImage}rev2.png`,
      description: "Variante coloreada de Revolution en HSB con paleta verde/vino: dos ángulos contrarrotantes tejen líneas con opacidad y grosor modulados por ruido Perlin (cada mitad con su propio índice de ruido) y, al cerrar la vuelta, rematan con una franja de líneas rotada en verde neón. Termina con noLoop().",
      tags: ["radial", "HSB", "Perlin noise", "noLoop"],
      controls: [{ key: "s", action: "Guardar el canvas como PNG (saveCanvas)." }],
      needsAudio: false,
      width: 1000,
      height: 1000,
    },
    factory: rev2,
  },
  {
    meta: {
      slug: "rev3",
      title: "Revolution III",
      author: "emm3",
      source: "creativeCode/rev3.js",
      image: `${baseImage}rev3.png`,
      description: "Pieza de timeline (≈30 s) por millis() con carácter cromático por fase: un atardecer ámbar con horizonte deformado por ruido Perlin da paso a un rayo verde neón con destellos ámbar y a un relieve orquídea trazado con ruido; entre fases se posan acentos geométricos tipo Kandinsky (círculos concéntricos, semicírculos, diagonales, retícula). Se detiene con noLoop(). Composición vertical.",
      tags: ["timeline", "atardecer", "Perlin noise", "Kandinsky", "HSB", "noLoop"],
      controls: [{ key: "s", action: "Guardar el canvas como PNG (saveCanvas)." }],
      needsAudio: false,
      width: 800,
      height: 1000,
    },
    factory: rev3,
  },
  {
    meta: {
      slug: "rev-noiz",
      title: "Sunset Revolution",
      author: "emm3",
      source: "creativeCode/revNoiz.js",
      image: `${baseImage}rev-noiz.png`,
      description: "Atardecer generativo en formato vertical (Instagram): degradado de sol y cielo por círculos interpolados (lerpColor) con el horizonte deformado por ruido Perlin, silueta de montaña que se acumula sobre la línea del horizonte, camino de relieve tipo joyplot que avanza hacia el espectador y rayos de luz que brotan del horizonte; timeline (~42 s) que termina con noLoop().",
      tags: ["timeline", "atardecer", "RGB", "lerpColor", "Perlin noise", "relieve", "noLoop"],
      controls: [{ key: "s", action: "Guardar el canvas como PNG (saveCanvas)." }],
      needsAudio: false,
      width: 1080,
      height: 1350,
    },
    factory: revNoiz,
  },
  {
    meta: {
      slug: "trayectorias",
      title: "Trayectorias",
      author: "emm3",
      source: "creativeCode/trayectorias.js",
      image: `${baseImage}trayectorias.png`,
      description: "Composición cyberpunk en capas translúcidas que se acumulan: anillos concéntricos deformados por ruido Perlin al fondo, una senoidal que baja de arriba hacia abajo, una figura de Lissajous central con períodos X/Y ajustables, y dos trayectorias que convergen en el centro-superior con brechas de líneas diagonales. Termina con noLoop().",
      tags: ["paramétrico", "Lissajous", "Perlin noise", "capas", "noLoop"],
      controls: [
        { key: "Período X", action: "Knob: cambia el período en X de la Lissajous (reinicia el trazo)." },
        { key: "Período Y", action: "Knob: cambia el período en Y de la Lissajous (reinicia el trazo)." },
        { key: "s", action: "Guardar el canvas como PNG (saveCanvas)." },
      ],
      needsAudio: false,
      width: 1000,
      height: 1000,
    },
    factory: trayectorias,
  },
  {
    meta: {
      slug: "sumador",
      title: "Sumador de Fourier",
      author: "mndrn.mx",
      source: "Talleres2021-CC2/assets/js/scripts/CC2/sumador.js",
      image: `${baseImage}sumador.png`,
      description: "Suma de armónicos hecha visible: la serie de Fourier dice que toda onda periódica se puede reconstruir sumando senoides puras (armónicos), f(t) = Σ aₙ·sin(nωt), donde cada término gira n veces más rápido que el fundamental y su amplitud aₙ es el coeficiente de Fourier de esa onda (p. ej. para una cuadrada aₙ = 4/(nπ) solo en los impares; para una sierra aₙ ∝ 1/n). Aquí cada senoide es un epiciclo: la columna muestra los primeros armónicos por separado (un círculo giratorio cada uno, con amplitud que decae por un factor) y, abajo, el plotter que los suma todos —al encimarlos, los círculos individuales van tejiendo la onda resultante en el tiempo. Cada armónico se tinta con un neón distinto y la suma total se resalta en naranja/cian. Reusa la biblioteca PloterFourier extendida. Sin audio.",
      tags: ["Fourier", "epiciclos", "armónicos", "serie de Fourier", "bibliotecas", "cyberpunk"],
      controls: [
        { key: "s", action: "Guardar el canvas como PNG (saveCanvas)." },
      ],
      needsAudio: false,
      width: 800,
      height: 600,
    },
    factory: sumador,
  },
  {
    meta: {
      slug: "spectografo",
      title: "Espectrógrafo de Fourier",
      author: "mdrn.mx",
      source: "creativeCode/spectografo.js",
      image: `${baseImage}spectografo.png`,
      description: "Visualizador de series de Fourier: dibuja los epiciclos (espirógrafo) cuyos radios siguen los coeficientes de siete ondas (triangular, cuadrada, sierra, senoidal, sierra inversa, pulso e impulso), y grafica en paralelo la onda resultante en el tiempo. Arranca con máximos armónicos y amplitud/velocidad medias; tres perillas controlan armónicos, amplitud y velocidad, y un recuadro de texto sobre el canvas muestra la onda actual y los parámetros. Restilizado a la paleta cyberpunk (estructura verde, figura naranja, onda cian). Interactivo, sin audio.",
      tags: ["Fourier", "epiciclos", "interactivo", "bibliotecas", "cyberpunk"],
      controls: [
        { key: "perillas", action: "Armónicos, amplitud y velocidad." },
        { key: "1–7", action: "Onda: triangular / cuadrada / sierra / senoidal / sierra inversa / pulso / impulso." },
        { key: "s", action: "Guardar el canvas como PNG (saveCanvas)." },
      ],
      needsAudio: false,
      width: 800,
      height: 500,
    },
    factory: spectografo,
  },
  {
    meta: {
      slug: "audio-graf",
      title: "Audio Graf",
      author: "mdrn.mx",
      source: "creativeCode/audioGraf.js",
      image: `${baseImage}audio-graf.png`,
      description: "Generador y analizador de audio: un oscilador cuya amplitud controla un ADSR (VCA principal: attack 1 s, decay 0 s, sustain 100 %, release 1.5 s), con su espectro FFT y forma de onda dibujados en tiempo real. Dos perillas centrales (frecuencia logarítmica y volumen) a 1/4 de la altura; el espectro usa un degradado cyberpunk verde→cian→naranja y el osciloscopio va en violeta. El sonido se toca con el mouse: clic dispara el ataque y soltar el release. Requiere activar el audio.",
      tags: ["audio", "oscilador", "FFT", "ADSR", "p5.sound", "cyberpunk"],
      controls: [
        { key: "clic", action: "Tocar: mantener pulsado sostiene la nota (ADSR); soltar la libera (activa el audio)." },
        { key: "perillas", action: "Frecuencia (log) y volumen, al centro a 1/4 de la altura." },
        { key: "1–4", action: "Onda: seno / triángulo / cuadrada / sierra." },
        { key: "l", action: "Alternar escala del espectro (lin/log)." },
        { key: "s", action: "Guardar el canvas como PNG (saveCanvas)." },
      ],
      needsAudio: true,
      width: 800,
      height: 600,
    },
    factory: audioGraf,
  },
  {
    meta: {
      slug: "delay3",
      title: "Delay III",
      author: "mdrn.mx",
      source: "creativeCode/delay3.js",
      image: `${baseImage}delay3.png`,
      description: "Escena audiovisual sobre el fundido de fondo original (negro → vino profundo en HSB): al tocar el canvas suena una campana FM (VCO FM → VCF pasa-banda resonante → VCA con envolvente AD percusiva → ping-pong delay) y se dibuja un círculo verde al centro; luego cada rebote del delay agrega un rombo de otro color a los lados, alternado como el ping-pong. Dos knobs inferiores controlan el tiempo y el feedback del delay: la opacidad de los rombos sigue el volumen del feedback y tiende a 0 cuanto más tardado es el eco. Retriggerear limpia y redibuja todo. Migrado a Tone.js.",
      tags: ["audio", "síntesis FM", "campana", "delay ping-pong", "Tone.js", "HSB", "interactivo"],
      controls: [
        { key: "clic", action: "Dispara la campana FM, limpia la escena y redibuja el círculo + los ecos (activa el audio)." },
        { key: "Delay time", action: "Knob: tiempo entre rebotes del ping-pong (y momento de aparición de cada rombo)." },
        { key: "Feedback", action: "Knob: realimentación del delay (nº y opacidad de los rombos)." },
        { key: "s", action: "Guardar el canvas como PNG (saveCanvas)." },
      ],
      needsAudio: true,
      motorAudio: "tone",
      width: 1000,
      height: 1000,
    },
    factory: delay3,
  }, 
  {
    meta: {
      slug: "synth",
      title: "Synth Modular",
      author: "emm3",
      source: "creativeCode/synth.js",
      image: `${baseImage}synth.png`,
      description: "Sintetizador modular monofónico: VCO1 (con paneo) + VCO2 (pulso) se suman en un mixer → VCF → VCA, con una única envolvente ADSR que gatea el VCA (attack al pulsar el mouse, release al soltar). Tras el VCA hay un delay ping-pong con controles de tiempo, feedback y mezcla. Cada módulo dibuja su osciloscopio/espectro con knobs giratorios; una franja de LEDs indica las voces activas y, al fondo, un vectorscopio X-Y traza las señales izquierda/derecha de la salida como figuras de Lissajous en vivo. Migrado a Tone.js con dispose explícito de todos los nodos. El sonido se inicia con el clic. Requiere activar el audio.",
      tags: ["audio", "síntesis", "VCO/VCF/VCA/ADSR", "delay ping-pong", "vectorscopio", "Tone.js"],
      motorAudio: "tone",
      controls: [
        { key: "clic", action: "Iniciar y tocar: al pulsar dispara el ataque del VCA; al soltar, el release (activa el audio)." },
        { key: "knobs VCO1", action: "Frecuencia, volumen y paneo de la voz 1." },
        { key: "knobs Delay", action: "Tiempo, feedback y mezcla del ping-pong." },
        { key: "1–4 / 8–0", action: "Voz del VCO1 / del VCO2 (pulso)." },
        { key: "w / l", action: "Onda↔espectro / escala lin↔log." },
        { key: "s", action: "Guardar el canvas como PNG (saveCanvas)." },
      ],
      needsAudio: true,
      width: 600,
      height: 760,
    },
    factory: synth,
  },
  // {
  //   meta: {
  //     slug: "piano",
  //     title: "Piano",
  //     author: "mndrn.mx",
  //     source: "Talleres2021-CC2/assets/js/scripts/CC2/piano.js",
  //     description:
  //       "Piano de 10 teclas con un oscilador square, envolvente, reverb y delay ping-pong. Clic en el canvas enciende el sistema; las teclas a s d f g h j k l ñ tocan las notas y pintan barras de color en HSB. Del taller de Audio y Web de mndrn.mx.",
  //     tags: ["audio", "síntesis", "oscilador", "p5.sound", "HSB"],
  //     controls: [
  //       { key: "clic", action: "Enciende/apaga el oscilador (activa el audio)." },
  //       { key: "a s d f g h j k l ñ", action: "Tocar las 10 notas del piano." },
  //       { key: "sliders", action: "Mezcla de delay y de reverb." },
  //     ],
  //     needsAudio: true,
  //     width: 500,
  //     height: 400,
  //   },
  //   factory: piano,
  // },
  {
    meta: {
      slug: "sound-collider",
      title: "Sound Collider",
      author: "mndrn.mx",
      source: "Talleres2021-CC2/assets/js/scripts/CC2/soundCollider.js",
      image: `${baseImage}sound-collider.png`,
      description: "Cajas que se desplazan y derivan con ruido; el usuario coloca hasta 8 bolitas detonadoras con el clic. Cuando una caja cruza una bolita dispara una voz de un sintetizador polifónico de campanitas (FM con envolvente AD percusiva, hasta 8 voces). El tamaño de la caja fija la nota (grande = grave, chica = aguda) y, con la cuantización activa, la nota se ajusta a la escala y nota base elegidas. UI: perillas de volumen y velocidad, botones de transposición MIDI ±, selector de nota base y escala, y botón de cuantización on/off. Migrado a Tone.js; la voz se elimina al cambiar de página.",
      tags: ["audio", "colisiones", "síntesis FM", "polifonía", "campanitas", "cuantización", "Tone.js", "bibliotecas"],
      motorAudio: "tone",
      controls: [
        { key: "clic", action: "Coloca una bolita detonadora (hasta 8) y arranca el audio." },
        { key: "perillas", action: "Volumen y velocidad de las cajas." },
        { key: "MIDI − / +", action: "Transponer la escala MIDI una octava abajo/arriba." },
        { key: "selectores", action: "Nota base y escala para la cuantización." },
        { key: "Cuantizar", action: "Activa/desactiva el ajuste de notas a la escala." },
        { key: "s", action: "Guardar el canvas como PNG (saveCanvas)." },
      ],
      needsAudio: true,
      width: 800,
      height: 600,
    },
    factory: soundCollider,
  },
  {
    meta: {
      slug: "fft-visualization",
      title: "Visualización FFT",
      author: "mndrn.mx",
      source: "Talleres2021-CC2/assets/js/scripts/CC2/fft_Visualization.js",
      image: `${baseImage}audiovisualization.png`,
      description: "Visualizador de audio sobre una canción: dibuja la autocorrelación de la forma de onda (curvas superiores, en naranja de acento) y un espectro de frecuencias en disposición polar de círculos y cuadrados, restilizado a la paleta cyberpunk del sitio. Detrás de todo, una animación de fondo audio-reactiva: un glow central que respira con los graves y una silueta de espectro reflejada. Botones Play/Stop/Random con hover naranja, perillas de volumen y velocidad, y la tecla t alterna entre la canción y el micrófono.",
      tags: ["audio", "FFT", "autocorrelación", "espectro", "p5.sound", "cyberpunk"],
      controls: [
        { key: "Play / Stop / Random", action: "Reproducir, detener o saltar en la canción." },
        { key: "perillas", action: "Volumen y velocidad de reproducción." },
        { key: "t", action: "Alternar entre la canción y el micrófono." },
        { key: "s", action: "Guardar el canvas como PNG (saveCanvas)." },
      ],
      needsAudio: true,
      width: 800,
      height: 600,
    },
    factory: fftVisualization,
  },
  // {
  //   meta: {
  //     slug: "reticula-crayola",
  //     title: "Retícula Crayola",
  //     author: "mndrn.mx",
  //     source: "Talleres2021-CC3/assets/js/scripts/CC3/Clase3/Ejemplo5.js",
  //     description:
  //       "Retícula 12×10 de colores estándar Crayola cargados de un JSON; al hacer clic sobre un círculo se muestra el nombre del color. Del taller de Código y Datos de mndrn.mx; el dataset se sirve localmente (public/crayola.json).",
  //     tags: ["datos", "JSON", "color", "interactivo", "Crayola"],
  //     controls: [
  //       { key: "clic", action: "Clic sobre un color muestra su nombre al centro." },
  //     ],
  //     needsAudio: false,
  //     width: 800,
  //     height: 600,
  //   },
  //   factory: reticulaCrayola,
  // },
  // {
  //   meta: {
  //     slug: "estacion-espacial",
  //     title: "Estación Espacial (ISS)",
  //     author: "mndrn.mx",
  //     source: "Talleres2021-CC3/assets/js/scripts/CC3/Clase4/Ejemplo8.js",
  //     description:
  //       "Mapea la posición en vivo de la Estación Espacial Internacional (API pública wheretheiss.at) sobre el canvas, con suavizado, encima de un GIF. Pieza de datos en tiempo real (basada en el ejemplo de la ISS de Daniel Shiffman). Requiere conexión a internet.",
  //     tags: ["datos", "API", "tiempo real", "mapa", "ISS"],
  //     controls: [
  //       { key: "—", action: "Pieza autónoma; consulta la posición de la ISS en vivo." },
  //     ],
  //     needsAudio: false,
  //     width: 800,
  //     height: 600,
  //   },
  //   factory: estacionEspacial,
  // },
  {
    meta: {
      slug: "terreno-ruido",
      title: "Terreno de Ruido",
      author: "emm3",
      source: "Code-Package-p5.js/02_M/M_1_4_01/sketch.js",
      image: `${baseImage}terreno-ruido.png`,
      description: "Malla 3D (WEBGL) tipo terreno generada con ruido Perlin, reestilizada al tema del sitio: cuerpo verde matrix con las cimas en naranja neón sobre fondo negro. Pieza autónoma con dos LFOs que modulan el relieve y giro lento en Z. Suma un DRON audio-reactivo en Tone.js: un super-saw polifónico toca la secuencia Am–F–Am–G en octavas bajas a través de un LPF estilo Moog con LFOs en el cutoff y la resonancia, mezclado con una voz de ruido blanco filtrada por un BPF (con LFO) cuyo volumen sigue el grado de ruido de la animación. Perilla de volumen máximo y botón de audio on/off con fundido continuo. Basada en Generative Design (cap. M).",
      tags: ["3D", "WEBGL", "Perlin noise", "terreno", "LFO", "dron", "super-saw", "Tone.js", "Generative Design"],
      motorAudio: "tone",
      controls: [
        { key: "Audio ON/OFF", action: "Activa/desactiva el dron con fundido continuo." },
        { key: "Vol. máx", action: "Perilla del volumen máximo de las dos voces." },
        { key: "arrastrar", action: "Inclinar/orbitar la cámara." },
        { key: "flechas / + −", action: "Falloff, octavas (suben el grado de ruido) y zoom." },
        { key: "espacio / s", action: "Nueva semilla / guardar PNG." },
      ],
      needsAudio: true,
      width: 600,
      height: 600,
    },
    factory: terrenoRuido,
  },
  {
    meta: {
      slug: "lineas-humo",
      title: "Líneas de Humo",
      author: "Generative Design",
      source: "Code-Package-p5.js/02_M/M_1_5_03/sketch.js",
      image: `${baseImage}lineas-humo.png`,
      description: "Miles de agentes siguen un campo de ruido Perlin 3D trazando líneas que se acumulan en contornos que fluyen, como humo o curvas de nivel. Reestilizado al tema del sitio: fondo oscuro con la mayoría de trazos en verde matrix y algunos destellos en naranja neón. Al hacer click, el número de agentes (1000–5000) se ajusta según la posición horizontal del mouse. Reusa la biblioteca AgenteHumo. Del libro Generative Design (cap. M).",
      tags: ["agentes", "flow field", "Perlin noise", "bibliotecas", "Generative Design"],
      controls: [
        { key: "click", action: "Nº de agentes (1000–5000) según mouseX." },
        { key: "1 / 2", action: "Alternar el modo de ruido." },
        { key: "c", action: "Nueva semilla de ruido." },
        { key: "borrar / s", action: "Limpiar la pantalla / guardar PNG." },
      ],
      needsAudio: false,
      width: 800,
      height: 800,
    },
    factory: lineasHumo,
  },
  {
    meta: {
      slug: "abanicos-agentes",
      title: "Abanicos de Agentes",
      author: "Generative Design",
      source: "Code-Package-p5.js/02_M/M_1_5_04/sketch.js",
      image: `${baseImage}abanicos-agentes.png`,
      description: "Miles de agentes siguen un campo de ruido y dibujan pinceladas en abanico, con trazo perpendicular (estilo 1) o elipses (estilo 2). Reestilizado al tema del sitio: fondo oscuro con la mayoría de pinceladas en verde matrix y algunos destellos en naranja neón. Al hacer click, el número de agentes (1000–5000) se ajusta según la posición horizontal del mouse. Reusa la biblioteca AgenteAbanico. Del libro Generative Design (cap. M).",
      tags: ["agentes", "flow field", "HSB", "bibliotecas", "Generative Design"],
      controls: [
        { key: "click", action: "Nº de agentes (1000–5000) según mouseX." },
        { key: "1 / 2 / 3", action: "Estilo de trazo: línea / elipse / rectángulo." },
        { key: "c", action: "Nueva semilla de ruido." },
        { key: "borrar / s", action: "Limpiar la pantalla / guardar PNG." },
      ],
      needsAudio: false,
      width: 800,
      height: 800,
    },
    factory: abanicosAgentes,
  },
  {
    meta: {
      slug: "ondas-moduladas",
      title: "Ondas Moduladas",
      author: "Generative Design",
      source: "Code-Package-p5.js/02_M/M_2_3_01/sketch.js",
      image: `${baseImage}ondas-moduladas.png`,
      description: "Un oscilador modulado en amplitud: la señal de información (seno, verde) y la portadora (coseno, verde tenue) se multiplican para dar la onda combinada, en naranja neón sobre fondo negro. La fase se anima sola de forma continua, así la onda se desplaza suavemente. Estudio de modulación del libro Generative Design (cap. M).",
      tags: ["oscilador", "modulación", "onda", "Generative Design"],
      controls: [
        { key: "i / c", action: "Mostrar/ocultar señal de información / portadora." },
        { key: "1 / 2 · 7 / 8", action: "Frecuencia · frecuencia de modulación." },
        { key: "← / → · s", action: "Empujar la fase (se anima sola) · guardar PNG." },
      ],
      needsAudio: false,
      width: 800,
      height: 400,
    },
    factory: ondasModuladas,
  },
  {
    meta: {
      slug: "orbitas-lissajous",
      title: "Órbitas de Lissajous",
      author: "Generative Design",
      source: "Code-Package-p5.js/02_M/M_2_3_02/sketch.js",
      image: `${baseImage}orbitas-lissajous.png`,
      description: "Curva de Lissajous modulada dibujada como órbitas elípticas entrelazadas en verde matrix sobre fondo oscuro; la fase se anima sola de forma continua y un texto en naranja muestra frecuencias, modulación y fase. La posición horizontal del mouse controla el número de puntos. Del libro Generative Design (cap. M).",
      tags: ["Lissajous", "paramétrico", "interactivo", "Generative Design"],
      controls: [
        { key: "mouse X", action: "Número de puntos de la curva." },
        { key: "p", action: "Pausar/continuar la animación de la fase." },
        { key: "d", action: "Alternar el modo de dibujo." },
        { key: "1-4 · 7-0 · ←/→", action: "Frecuencias, modulación y fase (se anima sola)." },
        { key: "s", action: "Guardar el canvas como PNG (saveCanvas)." },
      ],
      needsAudio: false,
      width: 600,
      height: 600,
    },
    factory: orbitasLissajous,
  },
  {
    meta: {
      slug: "malla-armonica",
      title: "Malla Armónica",
      author: "Generative Design",
      source: "Code-Package-p5.js/02_M/M_2_5_01/sketch.js",
      image: `${baseImage}malla-armonica.png`,
      description: "Una figura de Lissajous con sus puntos cercanos conectados: la malla de conexiones se dibuja en naranja neón (con desvanecimiento por distancia) y los nodos de la curva en verde matrix, sobre fondo oscuro. La fase rota sola de forma continua y suave, y un texto en naranja muestra frecuencias, modulación y fase. Del libro Generative Design (cap. M).",
      tags: ["Lissajous", "malla", "geometría", "animado", "Generative Design"],
      controls: [
        { key: "p", action: "Pausar/continuar la rotación de la fase." },
        { key: "1-4 · 7-0", action: "Frecuencias X/Y y de modulación." },
        { key: "← / →", action: "Empujar la fase (se anima sola)." },
        { key: "s", action: "Guardar el canvas como PNG." },
      ],
      needsAudio: false,
      width: 800,
      height: 800,
    },
    factory: mallaArmonica,
  },
    {
    meta: {
      slug: "atomos-pixel",
      title: "Átomos de Píxel",
      author: "emm3",
      source: "pixelAtomProject/pixelAtomProject.pde",
      image: `${baseImage}atomos-pixel.png`,
      description: "Port a p5 del sketch de Processing pixelAtomProject: captura una imagen (webcam o archivo), la descompone en partículas de color que conservan el píxel original y las anima con 15 modos —steering behaviors (seguir, deambular, manada, vórtice, explosión), composiciones generativas (líneas, círculos, rectángulos, hue-shift) y colonización de espacios— sobre 7 tipos de flow field con transiciones suaves, 9 formas de partícula (incluido ASCII/Matrix) y estelas/mezcla aditiva. Sin el control OSC del original.",
      tags: ["partículas", "steering", "webcam", "flow field", "ASCII", "interactivo"],
      controls: [
        { key: "1–9 / 0", action: "Modos: original, mouse, campo, deambular, lluvia, temblor, manada, vórtice, explosión, gravedad." },
        { key: "w / o / x / h / a", action: "Composiciones: líneas, círculos, rectángulos, hue-shift, colonización." },
        { key: "d e f g q y z", action: "Campos: ruido, imagen, radial, circular, corazón, infinito, espiral." },
        { key: "t / l / p / r", action: "Capturar / cargar imagen / play-pausa / reset." },
        { key: "s / b / m / n / v", action: "Forma, fondo/estelas, mezcla aditiva, tamaño dinámico, vida." },
        { key: "j k , .", action: "Tipografía: color, negrita, tamaño de letra." },
        { key: "espacio / ← ↑ → ↓ / + − / [ ] / u i / c", action: "Explosión, dirección lluvia, velocidad, estela, umbral colonización, ver campo." },
      ],
      needsAudio: false,
      width: 1280,
      height: 720,
    },
    factory: atomosPixel,
  },
  {
    meta: {
      slug: "flor-manos",
      title: "Flor de Manos",
      author: "emm3",
      source: "milpa/lib/sketches/florManos.ts",
      description: "Flor generativa que se abre y se cierra con las manos. Cuatro anillos de partículas en coordenadas polares (corazón, corona, semillas y pétalos) giran en sentidos contrarios sobre un fondo que deja estela, con la misma geometría de Spiral Gira. La diferencia: los parámetros no laten solos, los dicta un modelo de visión que lee las manos por la cámara — la pinza entre pulgar e índice estira los pétalos, los dedos levantados deciden cuántos son, separar las manos abre la flor, cerrar el puño la contrae, y la posición de la mano corre el color y la velocidad de giro. Sin cámara la pieza funciona igual con perillas; el recuadro de abajo a la derecha muestra qué está viendo el modelo.",
      tags: ["MediaPipe", "manos", "cámara", "IA", "espirales", "generativo", "interactivo"],
      image: `${baseImage}flor-manos.png`,
      controls: [
        { key: "Cámara", action: "Botón: enciende el rastreo y deja que las manos manden sobre los parámetros." },
        { key: "menú de cámara", action: "Elegir qué cámara usar; 'Buscar cámaras' pide permiso y muestra los nombres reales." },
        { key: "pinza", action: "Separar pulgar e índice: tamaño de los pétalos." },
        { key: "dedos", action: "Dedos levantados (ambas manos): número de pétalos, de 5 a 40." },
        { key: "manos", action: "Separar o juntar las dos manos: apertura de la flor (radio)." },
        { key: "puño", action: "Abrir o cerrar el puño: tamaño del corazón y densidad de las semillas." },
        { key: "posición", action: "Mover la mano: horizontal cambia el tono de los pétalos, vertical la velocidad de giro." },
        { key: "perillas", action: "Pétalos, tamaño, apertura, tono y giro — los mismos parámetros sin cámara." },
        { key: "HUD / h", action: "Mostrar u ocultar el preview de cámara y la lectura de gestos." },
        { key: "Guardar / s", action: "Guardar el canvas como PNG." },
      ],
      needsAudio: false,
      width: 900,
      height: 900,
    },
    factory: florManos,
  },
  {
    meta: {
      slug: "flor-shader",
      title: "Flor de Shader",
      author: "emm3",
      source: "milpa/lib/sketches/florShader.ts",
      image: `${baseImage}flor-shader.png`,
      description: "Flor de tres cuerpos en WEBGL sobre un fondo de oleaje, cada cuerpo con su textura procedural en GLSL —sin una sola imagen— y el tono ciclando en loop infinito. La corona de pétalos es una malla en forma de dona: un perfil polar de lóbulos (de 3 a 10 pétalos), ahuecado como cuenco, con nervaduras de ruido fractal, bandas iridiscentes que recorren rojos, rosas y violetas pero nunca verde, y un reflejo que persigue a la mano. En el hueco central flota un núcleo esférico de textura celular pulsante; del núcleo baja un tallo de cilindros verdes hacia el suelo, y detrás de todo ondula un mar de olas suaves. Las manos, leídas por la cámara, gobiernan los tres cuerpos: los dedos y la pinza rehacen los pétalos, separar las manos agranda el núcleo, subir la mano alarga el tallo. Y si cerrás los ojos, guarda la imagen. Sin cámara se maneja con las perillas.",
      tags: ["shader", "GLSL", "WEBGL", "malla", "dona", "MediaPipe", "manos", "parpadeo", "procedural", "flor"],
      controls: [
        { key: "Cámara", action: "Botón: enciende el rastreo y deja que las manos gobiernen los tres cuerpos." },
        { key: "menú de cámara", action: "Elegir qué cámara usar; 'Buscar cámaras' pide permiso y muestra los nombres reales." },
        { key: "dedos", action: "Dedos levantados (ambas manos): número de pétalos de la dona, de 3 a 10." },
        { key: "pinza", action: "Separar pulgar e índice: forma del pétalo, de redondo a afilado." },
        { key: "puño", action: "Abrir o cerrar el puño: cuánto se ahueca la corona (cuenco)." },
        { key: "manos", action: "Separar o juntar las dos manos: tamaño del núcleo esférico." },
        { key: "altura", action: "Subir o bajar la mano: largo del tallo hacia el suelo." },
        { key: "cerrar los ojos", action: "Con la cámara encendida, guarda la imagen (detección de parpadeo)." },
        { key: "perillas", action: "Pétalos, forma, cuenco, núcleo y tallo — los mismos parámetros sin cámara." },
        { key: "tono", action: "Cicla solo, en loop infinito (no hay control)." },
        { key: "HUD / h", action: "Mostrar u ocultar el preview de cámara y la lectura de gestos." },
        { key: "Guardar / s", action: "Guardar el canvas como PNG." },
      ],
      needsAudio: false,
      width: 900,
      height: 900,
    },
    factory: florShader,
  },
  {
    meta: {
      slug: "marea-manos",
      title: "Marea de Manos",
      author: "emm3",
      source: "milpa/lib/sketches/mareaManos.ts",
      image: `${baseImage}marea-manos.png`,
      description: "Un mar que se agita con la mano. Toda el agua vive en una textura de la GPU donde cada píxel guarda su velocidad, su presión y cuánta masa tiene; un shader la reescribe sesenta veces por segundo con cinco reglas de vecindad —advección, difusión de la presión, fuerza por su gradiente, realimentación por divergencia y conservación de masa, más gravedad— leyendo siempre el frame anterior desde un segundo lienzo oculto. El resultado se pinta como agua: la densidad da la profundidad del verde-azul, la pendiente de la superficie atrapa la luz y la velocidad enciende la espuma con destellos naranjas. Con la cámara encendida, la palma de la mano es el pincel que vierte agua, y abrir y cerrar el puño dispara un impulso radial: al cerrar, el mar se succiona hacia la mano; al abrir, sale despedido en una onda expansiva. Sin cámara se juega igual con el dedo sobre el lienzo y los botones de empujar y jalar.",
      tags: [
        "shader",
        "GLSL",
        "fluido",
        "simulación",
        "MediaPipe",
        "manos",
        "cámara",
        "mar",
      ],
      controls: [
        { key: "dedo / mouse", action: "Arrastrar sobre el agua: vierte agua nueva donde tocás." },
        { key: "Cámara", action: "Botón: enciende el rastreo de manos y la palma pasa a ser el pincel." },
        { key: "menú de cámara", action: "Elegir qué cámara usar; 'Buscar cámaras' pide permiso y muestra los nombres reales." },
        { key: "puño", action: "Cerrar el puño succiona el agua hacia la mano; abrirlo la empuja en una onda expansiva. El alcance crece si acercás la mano a la cámara." },
        { key: "Empujar / Jalar", action: "Botones: los mismos impulsos de explosión e implosión, sin cámara." },
        { key: "Pincel", action: "Perilla: radio del chorro de agua." },
        { key: "Impulso", action: "Perilla: fuerza del golpe radial del puño." },
        { key: "Gravedad", action: "Perilla: cuánto pesa el agua (en 0 la deja flotar)." },
        { key: "Espesor", action: "Perilla: viscosidad, de agua fina a fluido espeso." },
        { key: "Duración", action: "Perilla: cuánto dura el impulso antes de apagarse." },
        { key: "Limpiar / c", action: "Reinicia el campo y vuelve a sembrar el mar." },
        { key: "HUD / h", action: "Mostrar u ocultar el preview de cámara y la lectura de la mano." },
        { key: "Guardar / s", action: "Guardar el canvas como PNG." },
      ],
      needsAudio: false,
      width: 900,
      height: 600,
    },
    factory: mareaManos,
  },
  {
    meta: {
      slug: "mascara-tunel",
      title: "Máscara en el Túnel",
      author: "emm3",
      source: "milpa/lib/sketches/mascaraTunel.ts",
      image: `${baseImage}mascara-tunel.png`,
      description: "Tu cara se vuelve una máscara de 854 triángulos que viaja por un túnel curvo. El túnel no es geometría: cada píxel del fondo lanza un rayo que avanza a tientas hasta chocar con la pared de un tubo cuyo eje serpentea, y por un ramal lateral corre una brasa naranja. La máscara se texturiza con un plasma acumulativo congelado —dieciocho vueltas de un bucle que rota y pliega el plano hasta armar filamentos de color— encuadrado de modo que la zona más brillante y detallada cae siempre sobre la nariz. Aparece a media profundidad del tubo, se acerca hasta rozar la cámara y vuelve a empezar, iluminando la pared a su paso. Cerrar el ojo izquierdo salta a otro fotograma del plasma (otra textura, otros colores) y mantenerlo cerrado la hace derivar despacio; cerrar el derecho da un empujón que trae la máscara hacia adelante y aviva el destello. Sin cámara el túnel vuela igual y la máscara se sustituye por un plano con la misma textura.",
      tags: [
        "shader",
        "GLSL",
        "raymarching",
        "MediaPipe",
        "cara",
        "cámara",
        "túnel",
        "malla 3D",
      ],
      controls: [
        { key: "Cámara", action: "Botón: enciende el rastreo de cara y la máscara toma la forma de tu rostro." },
        { key: "menú de cámara", action: "Elegir qué cámara usar; 'Buscar cámaras' pide permiso y muestra los nombres reales." },
        { key: "cerrar el ojo izquierdo", action: "Salta a otro fotograma del plasma: la máscara cambia de textura y de colores. Sostenido, la textura deriva despacio." },
        { key: "cerrar el ojo derecho", action: "Empujón: la máscara salta hacia la cámara y sube el destello que arroja sobre el túnel." },
        { key: "Otra textura / t", action: "Botón: el mismo salto de textura que el ojo izquierdo, sin cámara." },
        { key: "Empujón / toque en el lienzo", action: "Botón o dedo sobre la imagen: el mismo empujón que el ojo derecho." },
        { key: "Plasma", action: "Perilla: elige el fotograma congelado de la textura (su semilla)." },
        { key: "Vuelo", action: "Perilla: velocidad a la que se recorre el túnel." },
        { key: "Acercar", action: "Perilla: velocidad del loop de profundidad de la máscara." },
        { key: "Lejos", action: "Perilla: a qué profundidad del túnel aparece la máscara." },
        { key: "Cerca", action: "Perilla: a qué distancia de la cámara termina su recorrido." },
        { key: "Destello", action: "Perilla: intensidad de la luz que la máscara arroja sobre la pared del tubo." },
        { key: "Tamaño", action: "Perilla: tamaño de la máscara dentro del túnel." },
        { key: "Brasa", action: "Botón: enciende o apaga la esfera naranja que corre por el tubo lateral." },
        { key: "HUD / h", action: "Mostrar u ocultar el preview de cámara y la lectura de los ojos." },
        { key: "Guardar / s", action: "Guardar el canvas como PNG." },
      ],
      needsAudio: false,
      width: 900,
      height: 600,
    },
    factory: mascaraTunel,
  },
  {
    meta: {
      slug: "fractal-julia",
      title: "Fractal de Julia",
      author: "emm3",
      source: "milpa/lib/sketches/fractalJulia.ts",
      image: `${baseImage}fractal-julia.png`,
      description: "Un conjunto de Julia que arde en colores vivos, con la forma y la paleta en tus manos y el brillo en tu voz. El fractal itera un número complejo hasta que escapa y se pinta tres veces con distintos encuadres superpuestos, todo en la GPU. El sonido entra por el micrófono: su espectro viaja al shader como una textura y enciende la intensidad y el glow de la imagen —cuanto más fuerte suena, más brilla—. La mano frente a la cámara manda el resto: moverla de lado a lado rota el tono y recorre el espectro cromático completo, y subirla o bajarla deforma el fractal barriendo el espacio de semillas. Sin cámara se juega con el mouse (X paleta, Y forma) y las perillas; sin micrófono, el brillo lo fija una perilla. La pieza sigue viva sin permisos.",
      tags: [
        "shader",
        "GLSL",
        "fractal",
        "Julia",
        "audio",
        "p5.sound",
        "MediaPipe",
        "manos",
        "cámara",
      ],
      controls: [
        { key: "mano ↔ (X)", action: "Con cámara: mover la mano de lado a lado rota el tono y cambia la paleta." },
        { key: "mano ↕ (Y)", action: "Con cámara: subir o bajar la mano deforma el fractal (su semilla)." },
        { key: "mouse", action: "Sin mano: arrastrar sobre el lienzo mueve la paleta (X) y la forma (Y)." },
        { key: "Micrófono / t", action: "Botón: enciende el micrófono; su sonido controla el brillo y el glow de la imagen." },
        { key: "Cámara", action: "Botón: enciende el rastreo de manos." },
        { key: "menú de cámara", action: "Elegir qué cámara usar; 'Buscar cámaras' pide permiso y muestra los nombres reales." },
        { key: "Sensib.", action: "Perilla: cuánto responde la intensidad al volumen del micrófono." },
        { key: "Intensidad", action: "Perilla: brillo base de la imagen (manda cuando no hay micrófono)." },
        { key: "Paleta", action: "Perilla: respaldo manual del tono cuando no hay mano ni mouse." },
        { key: "Forma", action: "Perilla: respaldo manual de la forma del fractal." },
        { key: "Calidad", action: "Perilla: iteraciones del fractal (más = más detalle y más costo)." },
        { key: "HUD / h", action: "Mostrar u ocultar el preview de cámara y el estado." },
        { key: "Guardar / s", action: "Guardar el canvas como PNG." },
      ],
      needsAudio: true,
      motorAudio: "p5.sound",
      width: 900,
      height: 600,
    },
    factory: fractalJulia,
  },
  {
    meta: {
      slug: "caverna-impulso",
      title: "Caverna a Impulsos",
      author: "emm3",
      source: "milpa/lib/sketches/cavernaImpulso.ts",
      image: `${baseImage}caverna-impulso.png`,
      description: "Un río subterráneo raymarcheado por el que avanzás a empujones. El túnel-caverna no es geometría: cada píxel lanza un rayo que serpentea por un tubo que respira, choca con una superficie de agua y la refracta —una segunda marcha— para ver el fondo a través de ella; una luz se mece por dentro (la esfera que la portaba se quitó, pero su resplandor viaja con ella). Lo distinto es cómo se avanza: el tiempo no corre solo. Cada impulso suma velocidad y la fricción la frena, así un empujón te hace planear unos pasos y varios seguidos aceleran de verdad. Empujás con el botón 'Adelante' (o tocando el lienzo) y, con la cámara encendida, acercando la mano de golpe hacia la lente: el tamaño aparente de la mano hace de sensor de profundidad. Un medidor muestra la fuerza acumulada. Sin cámara se juega igual con el botón y las perillas.",
      tags: [
        "shader",
        "GLSL",
        "raymarching",
        "caverna",
        "MediaPipe",
        "manos",
        "cámara",
        "impulso",
      ],
      controls: [
        { key: "Adelante / toque en el lienzo / espacio / ↑", action: "Un impulso hacia adelante; repetir acumula velocidad e inercia." },
        { key: "Cámara", action: "Botón: enciende el rastreo de manos; acercar la mano de golpe dispara un impulso." },
        { key: "menú de cámara", action: "Elegir qué cámara usar; 'Buscar cámaras' pide permiso y muestra los nombres reales." },
        { key: "Impulso", action: "Perilla: cuánta velocidad suma cada empujón." },
        { key: "Inercia", action: "Perilla: cuánto conserva la velocidad (fricción); más = planeás más lejos." },
        { key: "Vel. máx", action: "Perilla: tope de velocidad al insistir con los impulsos." },
        { key: "Calidad", action: "Perilla: pasos del raymarch (más = más detalle y más costo)." },
        { key: "Reiniciar / r", action: "Botón: vuelve el avance y la velocidad a cero." },
        { key: "HUD / h", action: "Mostrar u ocultar el preview de cámara y el estado." },
        { key: "Guardar / s", action: "Guardar el canvas como PNG." },
      ],
      needsAudio: false,
      width: 900,
      height: 600,
    },
    factory: cavernaImpulso,
  },
  {
    meta: {
      slug: "filtros-camara",
      title: "Filtros de Cámara",
      author: "emm3",
      source: "milpa/lib/sketches/filtrosCamara.ts",
      image: `${baseImage}filtros-camara.png`,
      description: "Un banco de filtros de post-proceso en GLSL que comen de la misma cámara, y que cambiás con el teclado o tocando el lienzo. Los cuatro shaders llegaron juntos de Shadertoy y todos reescriben la webcam píxel a píxel: 'Basura 2600' tejea la imagen y la cuantiza a una paleta de 8 colores estilo Atari con bloques de glitch; 'Rejilla de Onda' dibuja un caleidoscopio fractal recortado por el contorno (los bordes) de lo que ve la cámara; 'Espejo Complejo' deforma la imagen elevando la coordenada al cuadrado como número complejo; y 'Flujo Óptico' estima el movimiento entre el cuadro actual y el anterior (Lucas–Kanade) y lo pinta en color según su dirección. Una sola cámara viaja a todos como textura compartida, y el cuadro anterior queda guardado para los filtros que miran el tiempo. Dos perillas genéricas ajustan cada filtro (el HUD dice qué hacen) y hay un patrón de prueba animado para jugar sin cámara. Pensado para crecer: agregar un filtro es sumar una entrada al registro, sin tocar el pipeline.",
      tags: [
        "shader",
        "GLSL",
        "cámara",
        "post-proceso",
        "filtros",
        "flujo óptico",
        "glitch",
        "Shadertoy",
      ],
      controls: [
        { key: "1–4", action: "Elegir filtro directo: Basura 2600 / Rejilla de Onda / Espejo Complejo / Flujo Óptico." },
        { key: "toque en el lienzo / n / →", action: "Pasar al siguiente filtro." },
        { key: "←", action: "Filtro anterior." },
        { key: "Filtro ▸", action: "Botón: avanza al siguiente filtro (equivalente táctil)." },
        { key: "Ajuste 1 / Ajuste 2", action: "Perillas: los dos controles del filtro activo (el HUD indica qué hace cada uno)." },
        { key: "Velocidad", action: "Perilla: velocidad del reloj de los filtros animados." },
        { key: "Cámara", action: "Botón: enciende la webcam; apagada, un patrón de prueba anima la escena." },
        { key: "menú de cámara", action: "Elegir qué cámara usar; 'Buscar cámaras' pide permiso y muestra los nombres reales." },
        { key: "HUD / h", action: "Mostrar u ocultar el preview de cámara y el estado." },
        { key: "Guardar / s", action: "Guardar el canvas como PNG." },
      ],
      needsAudio: false,
      width: 900,
      height: 600,
    },
    factory: filtrosCamara,
  },
];

export function getSketch(slug: string): SketchEntry | undefined {
  return sketches.find((entry) => entry.meta.slug === slug);
}
